### ISSUE TITLE
nossl version

### ISSUE THREAD

**Issue by nicopace** [homewsn/homewsn.openwrt.packages#1]
Would be great to have the same support as mosquitto has, as it allows a very low storage footprint, as important as cpu and memory footprint on OpenWRT.

**Comment by homewsn** [comment]
I have not been using OpenWrt for quite some time now, and I don’t have OpenWrt Buildroot on hand. But does the menuconfig not allow you to make a choice between options? As far as I remember, the option without TLS(SSL) is available by default: https://github.com/homewsn/homewsn.openwrt.packages/blob/master/whsnbg/Config.in#L26

I found my very old whsnbg_1.2-1_ar71xx.ipk and whsnbg inside has a size only 45592 bytes. And, as far as I remember, there was included support for TLS(axTLS), MySQL and sensors.

**Comment by nicopace** [comment]
Hi! thanks for the quick reply!

By reading the the Makefile there is no nossl option, and it seems that by default it includes SSL.
Also, the dependencies are not included, so the package size is not a complete reference of the final image size.

**Comment by homewsn** [comment]
I see "nossl option" is by default. If you need tls-library just select the appropriate option.
Just see the Config.in:
https://github.com/homewsn/homewsn.openwrt.packages/blob/master/whsnbg/Config.in#L26
OpenWrt Makefile:
https://github.com/homewsn/homewsn.openwrt.packages/blob/master/whsnbg/Makefile#L49
whsnbg Makefile:
https://github.com/homewsn/whsnbg/blob/master/Makefile#L52
whsnbg build options:
https://github.com/homewsn/whsnbg#build-options-linux
